spring.profiles.active=dev
spring.jackson.generator.write-numbers-as-strings=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true